# name: Deploy with rsync over SSH

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Deploy via rsync over SSH
#         uses: appleboy/rsync-action@master
#         with:
#           host: ${{ secrets.FTP_SERVER }}             # Your server IP or domain
#           username: ${{ secrets.FTP_USERNAME }}       # SSH username
#           key: ${{ secrets.SSH_PRIVATE_KEY }}         # Your private SSH key
#           port: 22                                     # Optional: Change if not using port 22
#           source: "./"
#           target: "/home/ixzwwicdbh/petstravelinternational.com/"
#           args: "-avz --delete --exclude='.env'"
