name: Deploy with rsync over SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync files to server via rsync
        uses: appleboy/rsync-action@v0.1.2
        with:
          host: ${{ secrets.FTP_SERVER }}       # Your server IP or hostname
          username: ${{ secrets.FTP_USERNAME }} # SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }}   # SSH private key stored as secret
          # port: 22                              # Change if SSH uses another port
          source: "./"
          target: "/home/ixzwwicdbh/petstravelinternational.com/"              # Change to your server's web root
          args: "-avz --delete --exclude='.env'"
