name: Deploy with rsync over SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.FTP_SERVER }} >> ~/.ssh/known_hosts

      - name: Sync files to server using rsync
        run: |
          rsync -avz --delete --exclude=".env" ./ ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }}:/home/ixzwwicdbh/petstravelinternational.com/
